CREATE DATABASE EMPLOYEE;

USE EMPLOYEE;

CREATE TABLE EMPLOYEE(ID INT,NAME VARCHAR(100),SALARY INT);
DESCRIBE EMPLOYEE;
INSERT INTO EMPLOYEE(ID,NAME,SALARY) VALUES (1,"RAVI",50000);
INSERT INTO EMPLOYEE VALUES(2,"VARMA",60000);
INSERT INTO EMPLOYEE VALUES(20000,"RAVIVARMA",3);
INSERT INTO EMPLOYEE(SALARY,NAME,ID) VALUES(70000,"MILIESRAVI1",4);
INSERT INTO EMPLOYEE VALUES(1,"NAME1",10000),(6,"NAME2",20000);
SELECT * FROM EMPLOYEE;

CREATE TABLE MAXSAL(ID INT,NAME VARCHAR(100));
INSERT INTO MAXSAL(ID,NAME) SELECT ID,NAME FROM EMPLOYEE;
SELECT * FROM MAXSAL;
TRUNCATE MAXSAL;
INSERT INTO MAXSAL(ID,NAME) SELECT ID,NAME FROM EMPLOYEE WHERE SALARY>5000;
SET SQL_SAFE_UPDATES = 0;
UPDATE EMPLOYEE SET NAME="RAVIVARMA" WHERE ID=20000;

DELETE FROM EMPLOYEE WHERE NAME="RAVIVARMA";

CREATE TABLE LIST1(
ID INT,
NAME VARCHAR(50) NOT NULL,
PRICE INT NOT NULL DEFAULT 0
);

CREATE DATABASE FRUITSHOP;
USE FRUITSHOP;

CREATE TABLE FRUITSHOP(ID INT KEY AUTO_INCREMENT,NAME VARCHAR(50) NOT NULL,QUANTITY INT NOT NULL,COUNTER_NUMBER INT NOT NULL);
INSERT INTO FRUITSHOP(NAME,QUANTITY,COUNTER_NUMBER) VALUES("APPLE",12,101),("MANGO",13,102),("GRAPES",103,103);
CREATE TABLE APPLE(QUANTITY INT,COUNTER_NUMBER INT)
INSERT INTO APPLE(QUANTITY,COUNTER_NUMBER) SELECT QUANTITY,COUNTER_NUMBER FROM FRUITSHOP WHERE NAME="APPLE"
SELECT * FROM APPLE

CREATE TABLE GRAPES(QUANTITY INT,COUNTER_NUMBER INT)
INSERT INTO GRAPES(QUANTITY,COUNTER_NUMBER) SELECT QUANTITY,COUNTER_NUMBER FROM FRUITSHOP WHERE NAME="GRAPES"
SELECT * FROM GRAPES